language: go

sudo: required
dist: trusty

go:
  - "1.12"

env:
  - GO111MODULE=on

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get -u golang.org/x/lint/golint

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
