// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import protos "github.com/hieven/go-instagram/src/protos"

// Inbox is an autogenerated mock type for the Inbox type
type Inbox struct {
	mock.Mock
}

// Feed provides a mock function with given fields: _a0, _a1
func (_m *Inbox) Feed(_a0 context.Context, _a1 *protos.InboxFeedRequest) (*protos.InboxFeedResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *protos.InboxFeedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *protos.InboxFeedRequest) *protos.InboxFeedResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.InboxFeedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protos.InboxFeedRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
